server:
  port: 0
spring:
  application:
    name: PRODUCT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    instance-id: ${spring.application.name}:${instance-id:${random.value}}